BEGIN TRANSACTION;

DROP TABLE IF EXISTS WORDS CASCADE;
DROP SEQUENCE IF EXISTS WORDS_SEQ CASCADE;

CREATE SEQUENCE WORDS_SEQ START 1;

CREATE TABLE WORDS(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('WORDS_SEQ'),
  WORD TEXT NOT NULL
);

END TRANSACTION;