BEGIN TRANSACTION;

DROP TABLE IF EXISTS SENTENCES CASCADE;
DROP TABLE IF EXISTS GRAMMAR_RULE CASCADE;
DROP TABLE IF EXISTS WORDS CASCADE;
DROP TABLE IF EXISTS PICTURE CASCADE;
DROP TABLE IF EXISTS TEXTS CASCADE;
DROP TABLE IF EXISTS SINTAGM CASCADE;
DROP TABLE IF EXISTS RULE_TO_SENTENCE CASCADE;
DROP TABLE IF EXISTS TEXT_TO_SINTAGM CASCADE;
DROP TABLE IF EXISTS TEXT_TO_WORD CASCADE;
DROP TABLE IF EXISTS TEXT_TO_SENTENCE CASCADE;
DROP TABLE IF EXISTS SENTENCE_TO_SINTAGM CASCADE;
DROP TABLE IF EXISTS SENTENCE_TO_WORD CASCADE;


DROP SEQUENCE IF EXISTS SENTENCES_SEQ CASCADE;
DROP SEQUENCE IF EXISTS GRAMMAR_RULE_SEQ CASCADE;
DROP SEQUENCE IF EXISTS WORDS_SEQ CASCADE;
DROP SEQUENCE IF EXISTS PICTURE_SEQ CASCADE;
DROP SEQUENCE IF EXISTS TEXTS_SEQ CASCADE;
DROP SEQUENCE IF EXISTS SINTAGM_SEQ CASCADE;


CREATE SEQUENCE SENTENCES_SEQ START 1;
CREATE SEQUENCE GRAMMAR_RULE_SEQ START 1;
CREATE SEQUENCE WORDS_SEQ START 1;
CREATE SEQUENCE PICTURE_SEQ START 1;
CREATE SEQUENCE TEXTS_SEQ START 1;
CREATE SEQUENCE SINTAGM_SEQ START 1;


CREATE TABLE SENTENCES(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SENTENCES_SEQ'),
  SENTENCE_F TEXT NOT NULL,
  VIDEO_F BYTEA NOT NULL,
  AUDIO_F BYTEA NOT NULL
);

CREATE TABLE GRAMMAR_RULE(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('GRAMMAR_RULE_SEQ'),
  RULE_F TEXT NOT NULL,
  EXAMPLE_F TEXT NOT NULL
);

CREATE TABLE WORDS(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('WORDS_SEQ')/*,
  TEXT_ID BIGINT REFERENCES,
  SENTENCE_ID BIGINT REFERENCES SENTENCES(ID)*/
);

CREATE TABLE PICTURE(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('PICTURE_SEQ'),
  WORD_ID BIGINT REFERENCES WORDS(ID),
  PICTURE_F BYTEA NOT NULL
);

CREATE TABLE TEXTS(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('TEXTS_SEQ'),
  TEXT_F TEXT NOT NULL,
  VIDEO_F BYTEA NOT NULL,
  AUDIO_F BYTEA NOT NULL
);

CREATE TABLE SINTAGM(
  ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SINTAGM_SEQ'),
  SINTAGM_F TEXTS NOT NULL,
  SENTENCE_ID BIGINT REFERENCES SENTENCES(ID),
  VIDEO_F BYTEA NOT NULL,
  AUDIO_F BYTEA NOT NULL
);

CREATE TABLE RULE_TO_SENTENCE(
  SENTENCE_ID BIGINT REFERENCES SENTENCES(ID),
  RULE_ID BIGINT REFERENCES GRAMMAR_RULE(ID)
);

CREATE TABLE TEXT_TO_SINTAGM(
  SINTAGM_ID BIGINT REFERENCES SINTAGM(ID),
  TEXT_ID BIGINT REFERENCES TEXTS(ID)
);

CREATE TABLE TEXT_TO_WORD(
  TEXT_ID BIGINT REFERENCES TEXTS(ID),
  WORD_ID BIGINT REFERENCES WORDS(ID)
);

CREATE TABLE TEXT_TO_SENTENCE(
  SENTENCE_ID BIGINT REFERENCES SENTENCES(ID),
  TEXT_ID BIGINT REFERENCES TEXTS(ID)
);

CREATE TABLE SENTENCE_TO_SINTAGM(
  SENTENCE_ID BIGINT REFERENCES SENTENCES(ID),
  SINTAGM_ID BIGINT REFERENCES SINTAGM(ID)
);

CREATE TABLE SENTENCE_TO_WORD(
  SENTENCE_ID BIGINT REFERENCES SENTENCES(ID),
  WORD_ID BIGINT REFERENCES WORDS(ID)
);

END TRANSACTION;